version: "3.9"

services:
  db-service:
    image: postgres:15
    container_name: gestpro-erp-db-service
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gestpro_db
    ports:
      - "5432:5432"
    networks:
      - gestpro-network
    volumes:
      - db-data:/var/lib/postgresql/data  # Volumen persistente para PostgreSQL
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      sh -c "
      mkdir -p /var/lib/postgresql/data &&
      chown -R postgres:postgres /var/lib/postgresql/data &&
      su postgres -c '/usr/lib/postgresql/15/bin/postgres -D /var/lib/postgresql/data'
      "

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8002:8002"
    env_file:
      - .env
    networks:
      - gestpro-network
    depends_on:
      - db-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  gestpro-core:
    build:
      context: ./gestpro-erp-core
      dockerfile: Dockerfile
    container_name: gestpro-erp-core
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - gestpro-network
    depends_on:
      - db-service
      - auth-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  gestpro-network:
    driver: bridge

volumes:
  db-data:  # Define el volumen persistente para PostgreSQL
