version: "3.9"

services:
  gestpro-core:
    build:
      context: ./gestpro-erp-core
      dockerfile: Dockerfile
    container_name: gestpro-erp-core
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - gestpro-network
    depends_on:
      - db-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  db-service:
    build:
      context: ./db-service
      dockerfile: Dockerfile
    container_name: gestpro-erp-db-service
    ports:
      - "8001:8001"
    networks:
      - gestpro-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  gestpro-network:
    driver: bridge
