version: "3.9"
services:
  gestpro-core:
    build:
      context: ./gestpro-erp-core
      dockerfile: Dockerfile
    container_name: gestpro-erp-core
    ports:
      - "8000:8000"
    environment:
      - DATABASE_SERVICE_URL=http://db-service:8001/api/v1
    networks:
      - gestpro-network
    depends_on:
      - db-service

  db-service:
    build:
      context: ./db-service
      dockerfile: Dockerfile
    container_name: gestpro-erp-db-service
    ports:
      - "8001:8001"
    networks:
      - gestpro-network

networks:
  gestpro-network:
    driver: bridge
